### ISSUE TITLE
Config maps to obsolete flags

### ISSUE THREAD

**Issue by afranke** [kdeldycke/meta-package-manager#1358]
### What happened?

Follow [the documentation](https://kdeldycke.github.io/meta-package-manager/configuration.html) and add either

```
manager = ["flatpak", "pipx"]
```

or

```
exclude = [ "dnf",]
```
to your config file and run mpm. It will complain that you are using deprecated flags, like this:
```
warning: The `--include flatpak` option is deprecated. Use `--flatpak` single selector instead.
```
when it should map to `--<manager>` and `--no-manager`.

### Meta Package Manager configuration

```shell-session
I don’t know how to output something that would look ok in here. I tried various `-o` options, including plain, and it just seems to do nothing. I also think it is not relevant here.
```

### List package managers

```shell-session
Irrelevant?
```

### Binary path resolution

```shell-session
Irrelevant?
```

### Meta Package Manager version

```shell-session
mpm, version 5.18.0
```

**Comment by kdeldycke** [comment]
I agree, this situation is confusing. I just fix this upstream and updated the documentation accordingly.

It will be available in the v5.19.1 version that I plan to release in a couple of hours.
