### ISSUE TITLE
Use pip 9.0 JSON output

### ISSUE THREAD

**Issue by kdeldycke** [kdeldycke/meta-package-manager#18]
Table output makes parsing more predictable: https://pip.pypa.io/en/stable/reference/pip_list/#examples

And it's going to be the default in future releases:
```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
(...)
```

**Comment by tresni** [comment]
I'd suggest using `--format=json`, then parse with stdlib's `json.loads`

```
Contents/MacOS ●» pip list --outdated --format=json
[{"latest_filetype": "wheel", "version": "1.0.17", "name": "ipaddress", "latest_version": "1.0.18"}]
```

Parsing structured output is probably better then trying to do regex matching :)

**Comment by kdeldycke** [comment]
Good catch! That's more bullet-proof than parsing raw output.

I'll wait for a couple of `mpm` releases before implementing this. I don't want to force a hard-requirement on pip 9.0.x too soon.

**Comment by kdeldycke** [comment]
For reference, JSON output has been added in pip 9.0.0: https://github.com/pypa/pip/commit/5bbc73d145729d3c71b1ab07b7fc535732a819d0
