### ISSUE TITLE
Add install subcommand

### ISSUE THREAD

**Issue by kdeldycke** [kdeldycke/meta-package-manager#21]
Allow installation of a package. A manager must be provided.

**Comment by autinerd** [comment]
I would like to help with this, when more managers are implemented.

There could be 2 ways to installing a package:

1. `mpm install <manager>:<packagename>` or similar to install a package from a manager

2. `mpm install <packagename>` then mpm checks all implemented and installed managers for this package and the user has to select which manager to use

Also, mpm shall display to the user which packages are needed as a dependency to install before actually install the package, like apt does.

**Comment by kdeldycke** [comment]
@autinerd I like your proposal!

Feel free to propose a PR. You can start really small and implement only one manager for your proposed `install` command. See it as a first step. I don't require to have all manager supported for a new command as a first iteration.

Same thing for the two `<manager>:<packagename>` and `<packagename>` syntaxes. You can start implementing the easiest one and iterate on that.
