### ISSUE TITLE
Brew cask throws deprecation warning

### ISSUE THREAD

**Issue by SikhNerd** [kdeldycke/meta-package-manager#28]
<img width="681" alt="screen shot 2017-01-05 at 9 35 30 am" src="https://cloud.githubusercontent.com/assets/232652/21690745/66a3fd62-d32a-11e6-9ff6-8cb802a89e1c.png">

Switch to using `brew update` for cask instead of `brew cask update`

**Comment by kdeldycke** [comment]
For reference, here is the original PR: https://github.com/Homebrew/brew/pull/1690

This deprecated message appears starting Homebrew 1.1.6: https://github.com/Homebrew/brew/releases/tag/1.1.6

**Comment by kdeldycke** [comment]
Thanks @SikhNerd again! The fix will be part of the upcoming `mpm` 2.3.0 release.
