### ISSUE TITLE
mpm managers output misaligned

### ISSUE THREAD

**Issue by SikhNerd** [kdeldycke/meta-package-manager#30]
```
mpm, version 2.2.0
Terminal: iTerm 3.0.13
OS: 64bit Mac OS X 10.12.2 16C68
Kernel: x86_64 Darwin 16.3.0
Shell: bash 4.4.5
Resolution: 2560x1600
DE: Aqua
WM: Quartz Compositor
WM Theme: Graphite
Font: SourceCodePro-Regular 12
CPU: Intel Core i7-5557U CPU @ 3.10GHz
GPU: Intel Iris Graphics 6100
```

<img width="766" alt="screen shot 2017-01-05 at 1 25 27 pm" src="https://cloud.githubusercontent.com/assets/232652/21698131/7ad9a41a-d34a-11e6-924a-469cfcd3fe96.png">

**Comment by kdeldycke** [comment]
Ouch. That's ugly! :(

Probably an issue with the [`tabulate` package](https://bitbucket.org/astanin/python-tabulate/).

Can you track the root cause or any regression in [`tabulate` code](https://bitbucket.org/astanin/python-tabulate/src), its [commit log](https://bitbucket.org/astanin/python-tabulate/commits/) or [issues](https://bitbucket.org/astanin/python-tabulate/issues)?

**Comment by kdeldycke** [comment]
There might be a clue here: https://bitbucket.org/astanin/python-tabulate/issues/51/chinese-characters-using-fancy-grid

**Comment by SikhNerd** [comment]
Looks like that issue was resolved in tabulate handling double-width characters using the wcwidth library. FWIW, it's definitely those double-width check marks causing this: 

<img width="781" alt="screen shot 2017-01-12 at 4 56 43 pm" src="https://cloud.githubusercontent.com/assets/232652/21914425/21409db6-d8e8-11e6-94f5-671a1e0aa703.png">

**Comment by SikhNerd** [comment]
Maybe choose to sidestep this issue and use single-width marks like ✓ ?

<img width="755" alt="screen shot 2017-01-12 at 5 02 08 pm" src="https://cloud.githubusercontent.com/assets/232652/21914542/e2019564-d8e8-11e6-90b9-968dd0fb5f7e.png">

**Comment by kdeldycke** [comment]
The `✓` character is fine to me. Can you find a good alternative for the `❌` (as in https://github.com/kdeldycke/meta-package-manager/blob/v2.2.0/meta_package_manager/cli.py#L119).

**Comment by SikhNerd** [comment]
✘ looks pretty decent
