### ISSUE TITLE
mas upgrade command changes post 1.3.0

### ISSUE THREAD

**Issue by tresni** [kdeldycke/meta-package-manager#32]
mas version <1.3 you use `mas install [ID]` to upgrade a package.  Since version 1.3.0 this will return an error "package is already installed", instead the proper command is `mas upgrade [ID]`.   Need to get mas version (using `mas version`) and choose whether to do `install` or `upgrade` depending on version number.

**Comment by kdeldycke** [comment]
Good catch! Fixed in 72cccbe96b57bc7425376d0e6f638b483efb36b5.
