### ISSUE TITLE
Add backup & restore subcommand

### ISSUE THREAD

**Issue by sonhanguyen** [kdeldycke/meta-package-manager#38]
Currently I'm doing backup by piping to https://github.com/defunkt/gist. Would it be nice if we have the ability to sync/restore from a previously dumped package list? May as well be a good idea to ignore packages that are dependencies, even by manual select.

**Posible workflow:**
`mpm backup backup.json`
-> pop up editor
-> user manually pick what need to backup
-> dump json like usual with some packages marked as ignored
**Restore:**
`mpm restore backup.json`
-> bunch of `<package_manager> install <package>@<version>` (probably more complicated than that, but just installing is useful already for the migration use case)

Just an idea I wonder if you find useful enough to implement. I don't write enough `python` to call myself proficient at it, but if you think this is good and need a hand let me know.

**Comment by kdeldycke** [comment]
That's the ultimate feature of `mpm`! :) I's love to have that implemented as well. But there's still a lot of work and polishing needed. Like #21.

**Comment by kdeldycke** [comment]
For the context, here are Gist @sonhanguyen is referring:
* https://gist.github.com/sonhanguyen/4b8d795156f4f8747d66f023e6be66e1
* https://gist.github.com/sonhanguyen/e9a1a3d2195f179a51e84bac6583cd57
* https://gist.github.com/sonhanguyen/0ed181e366e835d32d980b435e798eeb

**Comment by kdeldycke** [comment]
The first iteration of a `backup` command has been added in https://github.com/kdeldycke/meta-package-manager/commit/c600ceeed93070ea89ac1479096192df747dd11b . It dumps the list of installed packages in a TOML file, as the later is easier to manually edit compared to a JSON file.

A dummy `restore` command has been added in https://github.com/kdeldycke/meta-package-manager/commit/6f594248378f5efcd89e8ee9e159fc2c9a614d4f .

The feature is far for fully implemented yet and needs at least #21 to be solved first before we can attempt to have this issue closed.
