### ISSUE TITLE
Broken with `click-log 0.2.0`

### ISSUE THREAD

**Issue by pdelre** [kdeldycke/meta-package-manager#39]
I ran `mpm upgrade` this morning which updated `click-log` for pip2. Since, `mpm` fails with the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 7, in <module>
    from meta_package_manager.cli import cli
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/cli.py", line 80, in <module>
    @click_log.init(logger)
AttributeError: 'module' object has no attribute 'init'
```

Looking into the `click-log` library, they indeed removed the `init` method: https://github.com/click-contrib/click-log/compare/31ab9063f45606edc89443c57129c2f82baf14c4...master#diff-816fea608d9f0e59fdac1ca0496203b3

**Comment by kdeldycke** [comment]
mpm 2.6.0 has just been released! :)

**Comment by pdelre** [comment]
Thank you! Upgrading went great!
