### ISSUE TITLE
No support for `dnf`?

### ISSUE THREAD

**Issue by Froggo8311** [kdeldycke/meta-package-manager#516]

**Comment by goodevilgenius** [comment]
When will this be included in the release on `pip`?

I saw this closed, and assumed it would already be available, but after installing on my fedora box, it's not there, and there's no `dnf.py` under `/usr/local/lib/python3.10/site-packages/meta_package_manager/managers/` where the other package managers are listed.

**Comment by kdeldycke** [comment]
I It has been pushed upstream today hence the auto-closing of that issue. It will be part of `mpm v4.12.0`. I'll make that release right away and should be available on PyPi via `pip` in a couple of minutes.
