### ISSUE TITLE
`scoop` support

### ISSUE THREAD

**Issue by autinerd** [kdeldycke/meta-package-manager#546]
Scoop https://scoop.sh/ is a package manager for Windows, similar to Chocolatey, but installs software as default in the user directory.

**Comment by autinerd** [comment]
I looked a bit, and it will be not so easy I think, because Scoop makes heavy use of special PowerShell stuff.

**Comment by kdeldycke** [comment]
Scoop support has been implemented upstream. It will be available in the upcoming release of mpm v5.7.0.
