### ISSUE TITLE
Add typehints

### ISSUE THREAD

**Issue by Hasnep** [kdeldycke/meta-package-manager#655]
Would you be interested in adding mypy style [typehints](https://docs.python.org/3/library/typing.html)? I find the IDE hints useful when using Python, and mypy/pyright could be set up to automatically check for errors. If you're interested, let me know and I'll try adding them to the repo where I can.

**Comment by kdeldycke** [comment]
Definitely!

This is not on my radar and I can live without. I'm worried more about the (constantly broken) state of CI and its complexity. I think having rock-solid multi-os, multi-distro, multi-python test suite will bring more stability and quality to the project. I guess it should be my priority then.

That being said, type hints in Python are free, can be gradually added, and is the general direction of the ecosystem. I never practiced them but it is my impression that type hints can points to edge-cases and highlights bugs. This will also bring quality, ease of contribution and tidiness to the project, especially if `mpm` starts to grow.

Nothing prevent us from working on both front simultaneously. So yes, feel free to iteratively add typehints here and there, I'll merge them right away! And don't try to be perfect: start with the easy parts! 😎

**Comment by kdeldycke** [comment]
I started working on that. I guess I'll have something to commit in the next couple of days. Seems easier that I was expecting.
