### ISSUE TITLE
Add config file to specify options

### ISSUE THREAD

**Issue by rkrug** [kdeldycke/meta-package-manager#66]
Thanks for a nice update, and the `-e` option.

But with the number of options increasing, it would be nice to be able to specify these in a config file, which is used to set these. It would than be possible to always use `mpm update` and use the options in the config file.

**Comment by kdeldycke** [comment]
I was thinking about that too but was going to wait for someone to explicitly ask for it before trying to implement. Didn't take long! ;) Thanks for the proposal, I'll try to implement it in the future.

**Comment by rkrug** [comment]
👍

**Comment by kdeldycke** [comment]
Just started to work on this, but realized I need https://github.com/pallets/click/pull/1329 to be released in upstream `click`. Seems to be planned for 8.0.0.
