### ISSUE TITLE
`purl` support (a.k.a. package URL)

### ISSUE THREAD

**Issue by pombredanne** [kdeldycke/meta-package-manager#669]
FYI, not a bug: These links of mine may be amusing or interesting to you:
- a universal syntax for package names and version https://github.com/package-url/purl-spec/ https://fosdem.org/2022/schedule/event/package_url_and_version_range_spec/ 
- another hackish script for https://xkcd.com/1654/ https://gist.github.com/pombredanne/d3585617882f91d9316be5ce5eddf190

**Comment by kdeldycke** [comment]
Now that's interesting. Thanks @pombredanne for the hints!

I have no objection adding some sort of purl support in `mpm`. It looks neat, active and documented. Bonus point: there's a [Python library available](https://github.com/package-url/packageurl-python).

What would be the ideal purl support in `mpm`? Do you have some ideas?

I guess we can start with supporting a minimal use-case. Maybe as a first step we can try to replace your "hackish script" with vanilla `mpm`. What this would looks like? What do you think of being able to do:

```shell-session
$ mpm --xkcd install  pkg:npm/left-pad pkg:pypi/boolean.py@3.7 pkg:deb/zlib1g-dev pkg:gem/bundler
```

**Comment by kdeldycke** [comment]
I just implemented support for purl for `install` subcommand. It will be available in the upcoming release of mpm 5.8.0.

@pombredanne, you'll be able to replace your `eclectic package manager (epm)` with mpm 5.8.0! 😉

More subcommand will support it in the future.

**Comment by pombredanne** [comment]
You positively rock!  :bow:

**Comment by kdeldycke** [comment]
@pombredanne mpm v5.8.0 has been released: https://twitter.com/kdeldycke/status/1577646239474139138
