### ISSUE TITLE
No Support for Pacaur

### ISSUE THREAD

**Issue by Froggo8311** [kdeldycke/meta-package-manager#816]
I have pacaur installed (I actually added an alias to my ~/.zshrc `alias pacman="pacaur --noedit"`), and I noticed that MPM does not provide compatibility for the Arch AUR packages via pacaur. Pacaur uses the exact same syntax and will also interface with standard pacman for installing non-AUR packages. 

Maybe have it detect if pacaur is installed, and if so, replace `pacman`'s entry with the path to the pacaur executable.

**Comment by Froggo8311** [comment]
Also: Pacaur does not allow you to use sudo, so perhaps automatically enable/disable sudo based on the pacmange manager.

**Comment by kdeldycke** [comment]
I just implemented upstream support for `pacaur`. It will be available in the upcoming release of mpm v5.9.0.
