### ISSUE TITLE
Create package manager groups

### ISSUE THREAD

**Issue by autinerd** [kdeldycke/meta-package-manager#820]
MPM now has support for `pacman` and multiple AUR helpers. Because all of the AUR helpers fully contain `pacman`s packages and all AUR helpers have completely the same packages (except someone adds other repos to an AUR helper), updates to a single package may show up multiple times. (If an AUR helper is installed, `pacman` is always installed as well); so all packages updatable by `pacman` are shown at least twice.

An idea would be to create a kind of "package manager group", so that only one of the group is used. (maybe with a hard-coded preference list, which can be overwritten by the user [maybe something like `--pacman-group yay`, when I want to use `yay` from the pacman group])

For example, we now have `paru` and `yay` as AUR helpers. We can group `paru`, `yay` and `pacman` into one group, with `pacman` only used when no other AUR helper is available.

**Comment by kdeldycke** [comment]
What do you think of fine-tuning this behaviour by simply excluding redundant managers depending on your usage?

For instance, if `yay` is your preferred helper and `pacman` is polluting your entries, you can setup a configuration file in `~/.config/mpm/config.toml` to exclude the other AUR helpers by default:
```toml
[mpm]
exclude = ["pacman", "paru"]
```

**Comment by kdeldycke** [comment]
Your case is a good example for a custom configuration, so I added to the documentation at: https://kdeldycke.github.io/meta-package-manager/configuration.html#overlapping-managers

**Comment by autinerd** [comment]
Thanks!
